//! `bridge` — the safe Rust wrapper over the DisasmStudio C engine.
//!
//! The raw `extern "C"` declarations are generated by bindgen (see `build.rs`)
//! into `$OUT_DIR/bindings.rs` and re-exported under the private `ffi` module.
//! Everything public here is a thin, panic-free, bounds-checked wrapper that
//! turns the flat POD records from `disasm.h` into owned Rust structs.
//!
//! Safety contract (per the engine ABI):
//!   * The engine never owns the image bytes; we keep the `Vec<u8>` alive for
//!     the whole `Engine` lifetime so the pointer handed to `ds_engine_create`
//!     stays valid until `Drop` calls `ds_engine_destroy`.
//!   * No engine call aborts/throws across the boundary; errors are int codes.
//!   * All fixed `char[N]` fields are read as bytes up to the first NUL.

#![allow(clippy::missing_safety_doc)]

mod ffi {
    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    #![allow(clippy::all)]
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

use std::ffi::CString;
use std::os::raw::c_char;
use std::ptr;

/// Target architecture. Ordinals match `ds_arch` (X86=0, X64=1, ARM=2, ARM64=3).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum Arch {
    X86 = 0,
    X64 = 1,
    Arm = 2,
    Arm64 = 3,
}

impl Arch {
    #[inline]
    fn to_ffi(self) -> ffi::ds_arch {
        self as ffi::ds_arch
    }
}

/// A loaded segment (name, RVA range, R/W/X permission flags).
#[derive(Debug, Clone)]
pub struct Segment {
    pub name: String,
    pub rva: u64,
    pub size: u64,
    pub flags: u32,
}

/// A decoded instruction.
#[derive(Debug, Clone)]
pub struct Insn {
    pub rva: u64,
    pub bytes: Vec<u8>,
    pub mnemonic: String,
    pub operands: String,
    /// Referenced address, or `None` when there is no reference.
    pub ref_target: Option<u64>,
    /// `DS_REF_*` ref-type tag.
    pub ref_type: u8,
}

/// A recovered function.
#[derive(Debug, Clone)]
pub struct Func {
    pub rva: u64,
    pub name: String,
    pub size: u64,
    pub block_count: u32,
    pub call_count: u32,
}

/// A cross-reference edge (`from -> to`, with a `DS_XREF_*` kind).
#[derive(Debug, Clone)]
pub struct Xref {
    pub from_rva: u64,
    pub to_rva: u64,
    pub kind: u8,
}

/// Engine-wide metadata snapshot.
#[derive(Debug, Clone)]
pub struct Meta {
    pub arch: u32,
    pub base: u64,
    pub entry: u64,
    pub image_size: u64,
    pub segment_count: usize,
    pub function_count: usize,
    pub instruction_count: usize,
}

/// Owning handle around a `*mut ds_engine`.
///
/// Holds the image `Vec<u8>` so the pointer passed to `ds_engine_create`
/// remains valid for the entire engine lifetime.
pub struct Engine {
    raw: *mut ffi::ds_engine,
    /// Kept alive solely so the engine's borrowed image pointer stays valid.
    _image: Vec<u8>,
}

// The engine is a self-contained handle with no thread-affine state; the shell
// moves it into a worker thread. The raw pointer is only ever touched behind a
// `&mut`/`&` discipline owned by the shell's `Mutex`, so this is sound.
unsafe impl Send for Engine {}

// `Sync` — concurrent `&Engine` decompilation is sound. `ds_decompile(e, rva)`
// constructs a FRESH `Decompiler` per call, reads a const engine (image + funcs),
// and shares only per-engine caches (sig table, PE tables, demangle map) that are
// each `std::mutex`-guarded (see decompiler.cpp: "the dump tool decompiles across
// N threads"). It never mutates the engine, so many threads may hold `&Engine` and
// call `decompile()` at once. Only `&self` methods are safe to call concurrently;
// the `&mut self` builders are still statically excluded by the borrow checker.
unsafe impl Sync for Engine {}

// ---- helpers ---------------------------------------------------------------

/// Read a fixed `char[N]` field (possibly un-terminated if it fills the array)
/// up to the first NUL into an owned `String`. Invalid UTF-8 is lossily
/// replaced rather than panicking.
fn cstr_field(buf: &[c_char]) -> String {
    // Reinterpret the signed-char slice as bytes, then cut at the first NUL.
    let end = buf.iter().position(|&c| c == 0).unwrap_or(buf.len());
    let bytes: Vec<u8> = buf[..end].iter().map(|&c| c as u8).collect();
    String::from_utf8_lossy(&bytes).into_owned()
}

/// Build a NUL-terminated `CString` from a `&str`, dropping any interior NULs
/// (so a malformed name can never truncate or fail the FFI call).
fn cstring(s: &str) -> CString {
    // Filter interior NULs to guarantee `CString::new` cannot error.
    let cleaned: Vec<u8> = s.bytes().filter(|&b| b != 0).collect();
    // SAFETY of unwrap: `cleaned` provably contains no NUL bytes.
    CString::new(cleaned).unwrap_or_else(|_| CString::new("").unwrap())
}

impl Engine {
    /// Create an engine over `image` laid out at RVAs, with the given image
    /// base and architecture. The `image` vector is moved in and kept alive.
    pub fn new(image: Vec<u8>, base: u64, arch: Arch) -> Engine {
        let ptr = image.as_ptr();
        let len = image.len();
        // `ds_engine_create` borrows the image; `_image` keeps it alive. If the
        // engine returns NULL (OOM) we still hold a valid (null) handle and all
        // subsequent methods guard on null, so nothing dereferences it.
        let raw = unsafe { ffi::ds_engine_create(ptr, len, base, arch.to_ffi()) };
        Engine { raw, _image: image }
    }

    #[inline]
    fn ok(&self) -> bool {
        !self.raw.is_null()
    }

    /// Mark the binary as a DLL (`true`) or EXE (`false`).
    pub fn set_is_dll(&mut self, b: bool) {
        if self.ok() {
            unsafe { ffi::ds_engine_set_is_dll(self.raw, if b { 1 } else { 0 }) };
        }
    }

    /// Explicitly set (and seed) the entry-point RVA.
    pub fn set_entry_rva(&mut self, rva: u64) {
        if self.ok() {
            unsafe { ffi::ds_engine_set_entry_rva(self.raw, rva) };
        }
    }

    /// Seed a segment (name, RVA, size, R/W/X flags).
    pub fn add_segment(&mut self, name: &str, rva: u64, size: u64, flags: u32) {
        if self.ok() {
            let c = cstring(name);
            unsafe { ffi::ds_engine_add_segment(self.raw, c.as_ptr(), rva, size, flags) };
        }
    }

    /// Seed a known symbol name for an RVA (highest-priority name source).
    pub fn add_symbol(&mut self, rva: u64, name: &str) {
        if self.ok() {
            let c = cstring(name);
            unsafe { ffi::ds_engine_add_symbol(self.raw, rva, c.as_ptr()) };
        }
    }

    /// Tell the engine the directory the binary was loaded from, so a PDB whose
    /// CodeView record baked a relative/bare filename can be resolved next to
    /// the binary instead of against the process CWD.
    pub fn set_pdb_dir(&mut self, dir: &str) {
        if self.ok() {
            let c = cstring(dir);
            unsafe { ffi::ds_engine_set_pdb_dir(self.raw, c.as_ptr()) };
        }
    }

    /// Seed a known function entry RVA (entry point, export, TLS callback).
    pub fn add_entry(&mut self, rva: u64) {
        if self.ok() {
            unsafe { ffi::ds_engine_add_entry(self.raw, rva) };
        }
    }

    /// Seed an import: bind `name` to the IAT slot `iat_rva` thunks dereference.
    pub fn add_import(&mut self, iat_rva: u64, name: &str) {
        if self.ok() {
            let c = cstring(name);
            unsafe { ffi::ds_engine_add_import(self.raw, iat_rva, c.as_ptr()) };
        }
    }

    // ---- analysis stages (each maps 0 -> Ok) ------------------------------

    fn stage(&mut self, code: i32, what: &str) -> Result<(), String> {
        if code == 0 {
            Ok(())
        } else {
            Err(format!("{} failed (engine code {})", what, code))
        }
    }

    /// Linear + recursive disassembly sweep.
    pub fn disassemble(&mut self) -> Result<(), String> {
        if !self.ok() {
            return Err("engine creation failed (null handle)".into());
        }
        let code = unsafe { ffi::ds_engine_disassemble(self.raw) };
        self.stage(code, "disassemble")
    }

    /// Function & basic-block recovery.
    pub fn build_cfg(&mut self) -> Result<(), String> {
        if !self.ok() {
            return Err("engine creation failed (null handle)".into());
        }
        let code = unsafe { ffi::ds_engine_build_cfg(self.raw) };
        self.stage(code, "build_cfg")
    }

    /// Name resolution priority chain.
    pub fn resolve_symbols(&mut self) -> Result<(), String> {
        if !self.ok() {
            return Err("engine creation failed (null handle)".into());
        }
        let code = unsafe { ffi::ds_engine_resolve_symbols(self.raw) };
        self.stage(code, "resolve_symbols")
    }

    /// Bidirectional cross-reference index.
    pub fn build_xrefs(&mut self) -> Result<(), String> {
        if !self.ok() {
            return Err("engine creation failed (null handle)".into());
        }
        let code = unsafe { ffi::ds_engine_build_xrefs(self.raw) };
        self.stage(code, "build_xrefs")
    }

    // ---- user annotations -------------------------------------------------

    /// Load user renames/comments from a JSON sidecar. Replaces the in-memory
    /// store; call after `build_cfg` so the identity hashes can bind.
    pub fn load_annotations(&mut self, path: &str) -> Result<(), String> {
        if !self.ok() {
            return Err("engine creation failed (null handle)".into());
        }
        let c = cstring(path);
        let code = unsafe { ffi::ds_engine_load_annotations(self.raw, c.as_ptr()) };
        self.stage(code, "load_annotations")
    }

    /// Write the user annotation store to a JSON sidecar.
    pub fn save_annotations(&mut self, path: &str) -> Result<(), String> {
        if !self.ok() {
            return Err("engine creation failed (null handle)".into());
        }
        let c = cstring(path);
        let code = unsafe { ffi::ds_engine_save_annotations(self.raw, c.as_ptr()) };
        self.stage(code, "save_annotations")
    }

    /// Rename and/or comment the function at `rva`. An empty str leaves that field.
    pub fn set_func_annotation(&mut self, rva: u64, name: &str, comment: &str) {
        if !self.ok() {
            return;
        }
        let (n, c) = (cstring(name), cstring(comment));
        unsafe { ffi::ds_engine_set_func_annotation(self.raw, rva, n.as_ptr(), c.as_ptr()) };
    }

    /// Rename a displayed local of the function at `rva` (`from` as printed).
    /// Define a struct the binary does not describe, so a variable typed
    /// `struct <name>*` both compiles and reads with real member names.
    /// `body` is the member list as C text; empty clears it.
    pub fn define_struct(&mut self, name: &str, body: &str) {
        if self.ok() {
            let n = cstring(name);
            let b = cstring(body);
            unsafe { ffi::ds_engine_define_struct(self.raw, n.as_ptr(), b.as_ptr()) };
        }
    }

    /// `set_var_type` through a SHARED handle.
    ///
    /// Every other engine mutator takes `&mut self`, which the shell cannot get:
    /// the session holds the engine behind an `Arc` so N threads can decompile at
    /// once. That is fine here and nowhere else, because the annotation store is
    /// the one piece of engine state with its own lock: `ds_engine_set_var_type`
    /// takes it to write, and `ds_engine_get_var_types` takes it to COPY out, so a
    /// write that reallocates the store cannot be observed half-done by a
    /// concurrent `decompile()`. Without that lock this would violate the `Sync`
    /// justification above and be a data race.
    pub fn set_var_type_shared(&self, rva: u64, var: &str, ty: &str) {
        if !self.raw.is_null() {
            let v = cstring(var);
            let t = cstring(ty);
            unsafe { ffi::ds_engine_set_var_type(self.raw, rva, v.as_ptr(), t.as_ptr()) };
        }
    }

    /// Set the C type of a display variable. Unlike `set_var_annotation` this
    /// changes decompilation: re-decompile the function to see the effect.
    /// An empty `ty` clears the override.
    pub fn set_var_type(&mut self, rva: u64, var: &str, ty: &str) {
        if self.ok() {
            let v = cstring(var);
            let t = cstring(ty);
            unsafe { ffi::ds_engine_set_var_type(self.raw, rva, v.as_ptr(), t.as_ptr()) };
        }
    }

    pub fn set_var_annotation(&mut self, rva: u64, from: &str, to: &str) {
        if !self.ok() {
            return;
        }
        let (f, t) = (cstring(from), cstring(to));
        unsafe { ffi::ds_engine_set_var_annotation(self.raw, rva, f.as_ptr(), t.as_ptr()) };
    }

    // ---- queries ----------------------------------------------------------

    /// Snapshot of engine-wide metadata.
    pub fn meta(&self) -> Meta {
        if !self.ok() {
            return Meta {
                arch: 0,
                base: 0,
                entry: 0,
                image_size: 0,
                segment_count: 0,
                function_count: 0,
                instruction_count: 0,
            };
        }
        let mut m: ffi::ds_meta = unsafe { std::mem::zeroed() };
        unsafe { ffi::ds_engine_get_meta(self.raw, &mut m as *mut ffi::ds_meta) };
        Meta {
            arch: m.arch as u32,
            base: m.base,
            entry: m.entry,
            image_size: m.image_size,
            segment_count: m.segment_count as usize,
            function_count: m.function_count as usize,
            instruction_count: m.instruction_count as usize,
        }
    }

    /// All segments, mapped into owned `Segment`s.
    pub fn segments(&self) -> Vec<Segment> {
        if !self.ok() {
            return Vec::new();
        }
        let count = unsafe { ffi::ds_segment_count(self.raw) } as usize;
        if count == 0 {
            return Vec::new();
        }
        let mut raw: Vec<ffi::ds_segment> = Vec::with_capacity(count);
        let written =
            unsafe { ffi::ds_get_segments(self.raw, raw.as_mut_ptr(), count) } as usize;
        let written = written.min(count);
        unsafe { raw.set_len(written) };
        raw.iter()
            .map(|s| Segment {
                name: cstr_field(&s.name),
                rva: s.rva,
                size: s.size,
                flags: s.flags,
            })
            .collect()
    }

    /// All recovered functions, mapped into owned `Func`s.
    pub fn functions(&self) -> Vec<Func> {
        if !self.ok() {
            return Vec::new();
        }
        let count = unsafe { ffi::ds_function_count(self.raw) } as usize;
        if count == 0 {
            return Vec::new();
        }
        let mut raw: Vec<ffi::ds_func> = Vec::with_capacity(count);
        let written =
            unsafe { ffi::ds_get_functions(self.raw, raw.as_mut_ptr(), count) } as usize;
        let written = written.min(count);
        unsafe { raw.set_len(written) };
        raw.iter()
            .map(|f| Func {
                rva: f.rva,
                name: cstr_field(&f.name),
                size: f.size,
                block_count: f.block_count,
                call_count: f.call_count,
            })
            .collect()
    }

    /// Total number of instructions in the linear listing.
    pub fn instruction_count(&self) -> usize {
        if !self.ok() {
            return 0;
        }
        unsafe { ffi::ds_instruction_count(self.raw) as usize }
    }

    /// Slice the linear listing by instruction index. `start`/`count` are
    /// clamped to the available range so this can never read out of bounds.
    pub fn disasm_range(&self, start: usize, count: usize) -> Vec<Insn> {
        if !self.ok() || count == 0 {
            return Vec::new();
        }
        let total = self.instruction_count();
        if start >= total {
            return Vec::new();
        }
        let avail = total - start;
        let want = count.min(avail);
        if want == 0 {
            return Vec::new();
        }
        let mut raw: Vec<ffi::ds_insn> = Vec::with_capacity(want);
        let written =
            unsafe { ffi::ds_disasm_range(self.raw, start, want, raw.as_mut_ptr()) } as usize;
        let written = written.min(want);
        unsafe { raw.set_len(written) };
        raw.iter()
            .map(|ins| {
                // `size` is clamped to the 16-byte byte buffer to be safe even
                // if the engine reports something nonsensical.
                let n = (ins.size as usize).min(ins.bytes.len());
                let bytes = ins.bytes[..n].to_vec();
                // DS_REF_NONE == 0 is fixed by the ABI (disasm.h); comparing to
                // the literal avoids depending on bindgen emitting that const.
                let ref_target = if ins.ref_type == 0 || ins.ref_target == 0 {
                    None
                } else {
                    Some(ins.ref_target)
                };
                Insn {
                    rva: ins.rva,
                    bytes,
                    mnemonic: cstr_field(&ins.mnemonic),
                    operands: cstr_field(&ins.operands),
                    ref_target,
                    ref_type: ins.ref_type,
                }
            })
            .collect()
    }

    /// Index of the instruction at-or-after `rva`, or `None` if there is none.
    pub fn index_for_rva(&self, rva: u64) -> Option<usize> {
        if !self.ok() {
            return None;
        }
        let idx = unsafe { ffi::ds_index_for_rva(self.raw, rva) };
        if idx == usize::MAX {
            None
        } else {
            Some(idx as usize)
        }
    }

    /// Read up to `len` raw bytes from the RVA-laid image starting at `rva`.
    ///
    /// The `_image` buffer is laid out by RVA (sections placed at their virtual
    /// addresses), so `image[rva..]` is exactly the in-memory view at `rva`.
    /// Returns fewer bytes (possibly empty) when the range runs past the image,
    /// never panicking. Used to render data-segment rows.
    pub fn read_bytes(&self, rva: u64, len: usize) -> Vec<u8> {
        let start = rva as usize;
        if start >= self._image.len() {
            return Vec::new();
        }
        let end = start.saturating_add(len).min(self._image.len());
        self._image[start..end].to_vec()
    }

    /// All cross-references pointing *to* `rva`.
    pub fn xrefs_to(&self, rva: u64) -> Vec<Xref> {
        if !self.ok() {
            return Vec::new();
        }
        let count = unsafe { ffi::ds_xrefs_to_count(self.raw, rva) } as usize;
        if count == 0 {
            return Vec::new();
        }
        let mut raw: Vec<ffi::ds_xref> = Vec::with_capacity(count);
        let written =
            unsafe { ffi::ds_get_xrefs_to(self.raw, rva, raw.as_mut_ptr(), count) } as usize;
        let written = written.min(count);
        unsafe { raw.set_len(written) };
        raw.iter()
            .map(|x| Xref {
                from_rva: x.from_rva,
                to_rva: x.to_rva,
                kind: x.kind as u8,
            })
            .collect()
    }
}

impl Engine {
    /// Decompile the function at `func_rva` to pseudo-C, or `None` if the rva is
    /// not a known function.
    pub fn decompile(&self, func_rva: u64) -> Option<String> {
        if !self.ok() {
            return None;
        }
        let ptr = unsafe { ffi::ds_decompile(self.raw, func_rva) };
        if ptr.is_null() {
            return None;
        }
        let s = unsafe { std::ffi::CStr::from_ptr(ptr as *const _) }
            .to_string_lossy()
            .into_owned();
        unsafe { ffi::ds_free_string(ptr) };
        Some(s)
    }
}

impl Drop for Engine {
    fn drop(&mut self) {
        if !self.raw.is_null() {
            unsafe { ffi::ds_engine_destroy(self.raw) };
            self.raw = ptr::null_mut();
        }
        // `_image` is freed after this, which is correct: the engine no longer
        // references the image once destroyed.
    }
}
